language: node_js
node_js:
  - 10
branches:
  only:
  - develop

install:
 - brew update >/dev/null
 - brew install glib mono openssl >/dev/null
 - curl -sSL -k -o osx-net-core.pkg https://download.visualstudio.microsoft.com/download/pr/59a7b78f-4e86-473b-b230-c84d15505cec/766e3e5f35e7bb9677dd785071c5fbf7/dotnet-sdk-2.1.500-osx-x64.pkg
 - sudo installer -pkg osx-net-core.pkg -target /
 - export PATH=/usr/local/share/dotnet:$PATH
 - npm install -q

script:
 - mono --version
 - dotnet --version
 - yarn test
 - EDGE_USE_CORECLR=1 yarn test

jobs:
  include:
    - stage: Produce Coverage
      node_js: node
      script: jest --coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage